Aarhus-Psychiatry-Research/psycop-ml-utils

.github/workflows/pytest.yml
README.md
src/timeseriesflattener/flattened_dataset.py
tests/add_outcome_tests.py
tests/test_add_outcome.py

Minimum viable product, simply for `add_outcome`! Let's see what you guys think ;-)
Primarily thinking about the API, but most of the methods implemented for `add_outcome` are near-mature as well.

add_outcome MVP

---

src/psycopmlutils/timeseriesflattener/flattened_dataset.py
tests/test_timeseriesflattener/test_add_values.py

`incident` boolean parameter for `add_outcome`

---

src/psycopmlutils/timeseriesflattener/flattened_dataset.py
tests/test_timeseriesflattener/test_add_values.py
tests/test_timeseriesflattener/test_resolve_multiple.py

Refactor out `self.df_aggregating` and add `keep_val_timestamp`

---

src/psycopmlutils/timeseriesflattener/flattened_dataset.py
tests/test_timeseriesflattener/test_min_date.py

feat: drop visits before `min_date`

---

src/psycopmlutils/loaders/load_demographics.py
src/psycopmlutils/timeseriesflattener/flattened_dataset.py
tests/test_timeseriesflattener/test_add_values.py
tests/test_timeseriesflattener/test_wrapper.py
tests/test_timeseriesflattener/utils_for_testing.py

feat: prefix for predictors and outcomes

---

README.md

Remove unused links in README.md

---

.gitignore
example/timeseriesflattener/generate_features_and_write_to_disk.py
pyproject.toml

- log filename and settings used to generate features to wandb
- save poetry.lock to wandb
- add the name of the current user as prefix in the feature file name
Fixes #135, #134

feat: add current user as prefix to feature file name. Fixes #134

---

example/loaders/load_physical_visits.py
example/timeseriesflattener/generate_features_and_write_to_disk.py
pyproject.toml
src/psycopmlutils/loaders/load_visits.py

Fixes #138.
@HLasse, just check that you think the implementation makes sense, I have sent the generated SQL strings to Bettina for error checking.

Martin bernstorff/update psychiatric physical visits loader

---

.darglint
pyproject.toml
src/psycopmlutils/loaders/load_diagnoses.py
src/psycopmlutils/loaders/load_ids.py
src/psycopmlutils/loaders/load_lab_results.py
src/psycopmlutils/loaders/load_medications.py
src/psycopmlutils/loaders/sql_load.py
src/psycopmlutils/model_performance/model_performance.py
src/psycopmlutils/model_performance/utils.py
src/psycopmlutils/timeseriesflattener/flattened_dataset.py
src/psycopmlutils/writers/sql_writer.py
tests/test_timeseriesflattener/test_errors.py

chore: fix all the darglint errors 🧹🥳

---

pyproject.toml
src/psycopmlutils/timeseriesflattener/data_integrity.py

Prune data integrity suite

---

.pre-commit-config.yaml
tests/test_timeseriesflattener/utils_for_testing.py

feat: move darglint to pre-commit

---

src/application/t2d/check_feature_set_integrity.py
src/psycopmlutils/utils.py

Move data generation save to E: drive

---

src/psycopmlutils/writers/sql_writer.py

Change SQL-writer to warn when using 'replace'

---

pyproject.toml
src/psycopmlutils/data_checks/raw/check_raw_df.py
src/psycopmlutils/loaders/raw/load_diagnoses.py
src/psycopmlutils/writers/sql_writer.py

- [ Y] I have battle-tested on Overtaci (RMAPPS1279)
- [Y] I have bumped the version as described in the [wiki](https://www.notion.so/Setting-up-Poetry-on-your-local-machine-76647d75e8fa4d9ba553cbc2a49946d9#dca1e0f2ce934a49acd1851aaf882d75)

feat: add way more loader functions

---

src/psycopmlutils/loaders/raw/load_diagnoses.py

feat: Small changes to data_loaders in load_diagnoses

---

pyproject.toml
src/psycopmlutils/loaders/raw/load_coercion.py

- [ X] I have bumped the version as described in the [wiki](https://www.notion.so/Setting-up-Poetry-on-your-local-machine-76647d75e8fa4d9ba553cbc2a49946d9#dca1e0f2ce934a49acd1851aaf882d75)

Added more data_loaders, fixed problem with new duplicate fix

---

pyproject.toml
src/psycopmlutils/loaders/raw/load_medications.py

Added more data loaders to medications.
Load_prescribed: Changed default option to "False", as this data is unstable and should be reflected upon before used. Maybe you have already discussed it?

feat: added more loaders to load_medications

---

src/psycopmlutils/synth_data_generator/synth_txt_data_generator.py
tests/test_data/synth_txt_data.csv

Fixes #190
Structure is similar to the _src/psycopmlutils/synth_data_generator/synth_data_generator.py_ script, but adapted to produce a column with chunks of generated texts - this is the main part for review.

Create sequential synthetic data

---

pyproject.toml
src/psycopmlutils/data_checks/flattened/feature_describer.py

add correct arg

---

.github/workflows/upload-to.pypi.yml
.gitignore

ci: upload to pushes to pypi

---

.gitignore
src/psycopmlutils/wandb/wandb_try_except_decorator.py

feat: add wandb decorator

---

.github/actions/test/action.yml
.github/workflows/main_test_and_release.yml
.gitignore
.pre-commit-config.yaml
pyproject.toml

build: remove poetry
